# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

permalink: /:title.html
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rogue
markdown: kramdown
disqus: ramnathk
google_analytics: dybll # UA-40935987-1

defaults:
  
    scope:
      path: "" # empty string for all files
    values:
      title: Yoga & the Techie

description: Saving the world one studio at a time
author:
  name: Karthikeyan R
  email: hello@krk.me
  twitter: ramnathk
  gplus: +KarthikeyanRamnath
  facebook: yogatechie
  linkedin: /in/ramnathk
  bio: Yoga Entrepreneur / Meditating Techie
  email_md5: 467b23e1344d5fc56d014ec826fddd82

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: 
